<?php
/**
 * Cyberwebeyeos — Big Tech Whitelist Sync (R34 T2.4)
 *
 * 4 büyük cloud sağlayıcısının resmi CIDR aralıklarını toplar:
 *   - Google:     https://www.gstatic.com/ipranges/goog.json
 *   - Cloudflare: https://www.cloudflare.com/ips-v4
 *   - Microsoft:  https://endpoints.office.com/endpoints/Worldwide?clientrequestid=<uuid>
 *   - AWS:        https://ip-ranges.amazonaws.com/ip-ranges.json
 *
 * Çıktı: bigtech_cidr.txt — pipe-separated:
 *   <cidr>|<provider>|<service>|<last_updated>
 *
 * Modlar:
 *   CLI: php bigtech_whitelist_sync.php [--dry] [--quiet]
 *   Web: POST /bigtech_whitelist_sync.php  (RBAC admin)
 *
 * Cron örneği (haftalık pazar 03:00):
 *   0 3 * * 0 /usr/bin/php /var/www/html/bigtech_whitelist_sync.php --quiet
 */

require_once __DIR__ . '/ioc_helpers.php';

$IS_CLI = (php_sapi_name() === 'cli');
$BIGTECH_FILE = __DIR__ . '/bigtech_cidr.txt';

$DRY = false; $QUIET = false; $WEB_OWNER = '';
if ($IS_CLI) {
    foreach ($argv as $a) {
        if ($a === '--dry' || $a === '-n') $DRY = true;
        if ($a === '--quiet' || $a === '-q') $QUIET = true;
    }
} else {
    require_once __DIR__ . '/blacklist_admin_auth.php';
    require_once __DIR__ . '/audit_log.php';
    require_role(['admin']);
    if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
        http_response_code(405);
        header('Content-Type: application/json');
        echo json_encode(['ok'=>false,'error'=>'POST required']); exit;
    }
    header('Content-Type: application/json; charset=utf-8');
    $DRY = !empty($_POST['dry']);
    $WEB_OWNER = cwe_current_user() ?: 'web';
}

function _fetch_url(string $url, int $timeout = 12): ?string {
    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_TIMEOUT => $timeout,
        CURLOPT_FOLLOWLOCATION => true,
        CURLOPT_USERAGENT => 'cyberwebeyeos-tip/1.0',
        CURLOPT_SSL_VERIFYPEER => true,
    ]);
    $body = curl_exec($ch);
    $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    return ($code === 200 && $body) ? $body : null;
}

$now = date('Y-m-d H:i:s');
$out_lines = ['# Big Tech CIDR Whitelist — auto-generated by bigtech_whitelist_sync.php'];
$out_lines[] = "# Last sync: $now";
$out_lines[] = '# Format: <cidr>|<provider>|<service>|<sync_ts>';

$stats = ['google'=>0, 'cloudflare'=>0, 'microsoft'=>0, 'aws'=>0, 'errors'=>[]];

// --- Google ---
$body = _fetch_url('https://www.gstatic.com/ipranges/goog.json');
if ($body) {
    $j = json_decode($body, true);
    foreach (($j['prefixes'] ?? []) as $p) {
        $cidr = $p['ipv4Prefix'] ?? ($p['ipv6Prefix'] ?? '');
        if ($cidr) {
            $out_lines[] = "{$cidr}|google|gcp|{$now}";
            $stats['google']++;
        }
    }
} else { $stats['errors'][] = 'google: fetch failed'; }

// --- Cloudflare (plain text, IPv4 only) ---
$body = _fetch_url('https://www.cloudflare.com/ips-v4');
if ($body) {
    foreach (preg_split('/\r?\n/', $body) as $line) {
        $line = trim($line);
        if ($line === '' || $line[0] === '#') continue;
        if (preg_match('#^(\d+\.\d+\.\d+\.\d+/\d+)$#', $line)) {
            $out_lines[] = "{$line}|cloudflare|cdn|{$now}";
            $stats['cloudflare']++;
        }
    }
} else { $stats['errors'][] = 'cloudflare: fetch failed'; }

// --- Microsoft (Office endpoints — Worldwide service area) ---
$ms_uuid = sprintf('%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
    mt_rand(0,0xffff), mt_rand(0,0xffff),
    mt_rand(0,0xffff),
    mt_rand(0,0x0fff) | 0x4000,
    mt_rand(0,0x3fff) | 0x8000,
    mt_rand(0,0xffff), mt_rand(0,0xffff), mt_rand(0,0xffff)
);
$body = _fetch_url('https://endpoints.office.com/endpoints/Worldwide?clientrequestid=' . $ms_uuid);
if ($body) {
    $j = json_decode($body, true);
    $seen = [];
    foreach (($j ?? []) as $svc) {
        $svc_name = $svc['serviceArea'] ?? 'unknown';
        foreach (($svc['ips'] ?? []) as $cidr) {
            if (isset($seen[$cidr])) continue;
            $seen[$cidr] = true;
            $out_lines[] = "{$cidr}|microsoft|{$svc_name}|{$now}";
            $stats['microsoft']++;
        }
    }
} else { $stats['errors'][] = 'microsoft: fetch failed'; }

// --- AWS ---
$body = _fetch_url('https://ip-ranges.amazonaws.com/ip-ranges.json');
if ($body) {
    $j = json_decode($body, true);
    foreach (($j['prefixes'] ?? []) as $p) {
        $cidr = $p['ip_prefix'] ?? '';
        $svc = $p['service'] ?? 'AMAZON';
        if ($cidr) {
            $out_lines[] = "{$cidr}|aws|{$svc}|{$now}";
            $stats['aws']++;
        }
    }
} else { $stats['errors'][] = 'aws: fetch failed'; }

$total = $stats['google'] + $stats['cloudflare'] + $stats['microsoft'] + $stats['aws'];

$payload = ['ok'=>true, 'total'=>$total, 'stats'=>$stats, 'dry'=>$DRY];

if ($DRY) {
    $payload['message'] = '[DRY] Yazma yapılmadı';
    if ($IS_CLI) { if (!$QUIET) print_r($payload); exit(0); }
    echo json_encode($payload); exit;
}

// Atomic write
$tmp = $BIGTECH_FILE . '.tmp';
if (file_put_contents($tmp, implode("\n", $out_lines) . "\n") === false) {
    $payload = ['ok'=>false, 'error'=>'Yazma başarısız'];
    if ($IS_CLI) { fwrite(STDERR, $payload['error']."\n"); exit(2); }
    echo json_encode($payload); exit;
}
rename($tmp, $BIGTECH_FILE);
@chmod($BIGTECH_FILE, 0664);

$payload['message'] = "✅ {$total} CIDR sync edildi (G:{$stats['google']} CF:{$stats['cloudflare']} MS:{$stats['microsoft']} AWS:{$stats['aws']})";

if (function_exists('audit_log_event')) {
    audit_log_event('bigtech_sync', ['total'=>$total, 'stats'=>$stats, 'owner'=>$WEB_OWNER ?: 'cron']);
}

if ($IS_CLI) { if (!$QUIET) print_r($payload); exit(0); }
echo json_encode($payload, JSON_UNESCAPED_UNICODE);
